//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Magners.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Image
    {
        public Image()
        {
            this.Copies = new HashSet<Copy>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Tags { get; set; }
        public string ImageType { get; set; }
    
        public virtual ICollection<Copy> Copies { get; set; }
    }
}
